### ISSUE TITLE
Is this version of RefineDet cpu-used only

### ISSUE THREAD

**Issue by NogizakaDaisuki** [fukatani/RefineDet_chainer#1]
Thanks for sharing the RefineDet chainer version.
And I have a question about that ss this version of RefineDet cpu-used only?
If I want to use gpu in it what should I do?

Looking forward to your favourable reply.

**Comment by fukatani** [comment]
Please try `python train.py --model refinedet320 --batchsize 22 --gpu 0`

You can select gpu id by --gpu option.

**Comment by fukatani** [comment]
Unfortunately, I haven't succeeded original RefineDet performance by this implementation.

**Comment by NogizakaDaisuki** [comment]
Thanks for your reply , I got it.
One more question, how can I use the model to inference a picture?

**Comment by fukatani** [comment]
I haven't prepare inference script yet.
I think https://github.com/chainer/chainercv/blob/master/examples/ssd/demo.py is useful if we want to inference pictures.

**Comment by NogizakaDaisuki** [comment]
Okay，thank you very much !
As all my problem were solved , I will close this issue
