### ISSUE TITLE
ImportError: cannot import name SSD300Plus

### ISSUE THREAD

**Issue by NogizakaDaisuki** [fukatani/RefineDet_chainer#2]
There is a error when I tried to train my model:

<root@987f09a2c08e:/RefineDet_chainer/refinedet# python train.py --model refinedet320 --batchize 22
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from chainercv.links import SSD300Plus
ImportError: cannot import name SSD300Plus>

I checked the chainer's code, I found no SSD300Plus but a similar class named "SSD300" in chainercv/links/__init__py. Is it the right one?

**Comment by fukatani** [comment]
Thank you for your report!
I fixed train.py.
Could you git pull and retry refinedet?
